name: Build test bundle

# can adding branch or path constraints
on: [ push, pull_request ]

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
      - name: Setup java sdk
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set flutter sdk version number env
        run: echo "FLUTTER_SDK_VERSION=$(yq r pubspec.yaml environment.flutter)" >> $GITHUB_ENV
      - run: echo "💡 repo use flutter version is ${{ env.FLUTTER_SDK_VERSION }}."
      - name: Cache flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_SDK_VERSION }}
      - name: Setup flutter sdk
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_SDK_VERSION }}
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build apk --profile
      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: test-apk
          path: build/app/outputs/flutter-apk/app-profile.apk
      - name: send to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_NOTICE_GROUP_ID }}
          token: ${{ secrets.TG_TOKEN_LIAO_HELPER_BOT }}
          message: |
            flutter_build_action_samples android 测试包
            branch: ${GITHUB_REF##*/}
            last commit msg: ${{ github.event.commits[0].message }}
            last commit author: ${{ github.actor }}

            download with: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

#  build-ios-bundle:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "🎉 TODO."