name: Build test bundle

# can adding branch or path constraints
on:
  push:
    branches:
      - master

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
      - name: Setup java sdk
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set flutter sdk version number env
        run: echo "FLUTTER_SDK_VERSION=$(yq r pubspec.yaml environment.flutter)" >> $GITHUB_ENV
      - run: echo "💡 repo use flutter version is ${{ env.FLUTTER_SDK_VERSION }}."
      - name: Cache flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_SDK_VERSION }}
      - name: Setup flutter sdk
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_SDK_VERSION }}
      - run: echo "💡 commits 0 messge ${{ github.event.commits[0].message }}"
      - run: echo "💡 pr title ${{ github.event.pull_request.title }}"
      - run: echo "💡 github ref ${{ github.ref }}"
      - run: echo "💡 ${{ github.head_ref }} into ${{ github.base_ref }}"
#      - run: flutter --version
#      - run: flutter clean
#      - run: flutter pub get
#      - run: flutter pub upgrade
#      - run: flutter build apk --profile --verbose
#      - run: echo "APP_VERSION=$(yq r pubspec.yaml version)" >> $GITHUB_ENV
#      - name: Upload apk file
#        uses: actions/upload-artifact@v1
#        with:
#          name: action-test-${{ env.APP_VERSION }}
#          path: build/app/outputs/flutter-apk/app-profile.apk
      - name: send to telegram
        if: 1 != 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_NOTICE_GROUP_ID }}
          token: ${{ secrets.TG_TOKEN_LIAO_HELPER_BOT }}
          message: |
            **flutter_build_action_samples android test apk APP_VERSION**
            branch: ${{ github.ref }}
            last commit info: ${{ github.event.commits[0].message }} - ${{ github.actor }}

            download with: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

#  build-ios-bundle:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "🎉 TODO."
