name: Console log

on:
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "💡 Start"
      - run: echo "💡 commits 0 is ${{ github.event.commits[0] }}"
      - run: echo "💡 commits 0 message is ${{ github.event.commits[0].message }}"
      - run: echo "💡 head_commit is ${{ github.event.head_commit }}"
      - run: echo "💡 head_commit message is ${{ github.event.head_commit.message }}"
      - run: echo "💡 actor is ${{ github.actor }}"
      - run: echo "💡 ref is ${{ github.event.ref }}"
      - run: echo "💡 ref_name is ${{ github.event.ref_name }}"
      - run: echo "💡 event is ${{toJSON(github.event)}}"
      - run: echo "💡 github is ${{toJSON(github)}}"
      - name: Obtain commit info
        run: |
          echo "FIRST_COMMIT_MESSAGE=$(git log --no-merges -n 1 --pretty=format:%s)" >> $GITHUB_ENV
          echo "FIRST_COMMIT_AUTHOR=$(git log --no-merges -n 1 --pretty=%an)" >> $GITHUB_ENV
      - run: echo "💡 FIRST_COMMIT_MESSAGE is ${{ env.FIRST_COMMIT_MESSAGE }}"
      - run: echo "💡 FIRST_COMMIT_MESSAGE is ${{ env.FIRST_COMMIT_AUTHOR }}"
      - run: echo "💡 End"
