name: Feature test

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: macos-latest
    steps:
      - name: test request tg
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.telegram.org/bot${{ secrets.TG_TOKEN_LIAO_HELPER_BOT }}/sendMessage'
          method: 'POST'
          chat_id: ${{ secrets.TG_NOTICE_GROUP_ID }}
          text: 'title%0A%0Acontent'